apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: allistore-db
  namespace: default
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  replicas: 1
  selector:
    matchLabels:
      app: allistore-db
  serviceName: allistore-db
  template:
    metadata:
      labels:
        app: allistore-db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: saleor
        - name: POSTGRES_USER
          value: saleor
        image: library/postgres:13-alpine
        imagePullPolicy: IfNotPresent
        name: allistore-db
        ports:
        - containerPort: 5432
          name: allistore-db
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: storage
        - mountPath: /docker-entrypoint-initdb.d
          name: replica-user
      volumes:
      - configMap:
          defaultMode: 420
          name: replica-user
        name: replica-user
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: storage
    spec:
      accessModes:
      - ReadWriteOnc
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
