apiVersion: v1
kind: Service
metadata:
  name: webserver
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: webserver
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP