steps:
  # Check and Build for Saleor Core
  - name: 'gcr.io/cloud-builders/git'
    id: 'Check Saleor Core'
    entrypoint: 'bash'
    args:
    - '-c'
    dir: 'saleor-core/'

#   # Check and Build for Saleor Dashboard
#   - name: 'gcr.io/cloud-builders/git'
#     id: 'Check Saleor Dashboard'
#     entrypoint: 'bash'
#     args:
#     - '-c'
#     - |
#       if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'dashboard/'; then
#         echo "Changes detected in Dashboard, proceeding with build."
#         gcloud builds submit --config=dashboard/cloudbuild.yaml --substitutions=_SERVICE_NAME="saleor-dashboard",_DOCKERFILE_PATH="dashboard/Dockerfile",_BUILD_CONTEXT="dashboard"
#       else
#         echo "No changes in Dashboard, skipping build."
#       fi
#     dir: 'dashboard/'

#   # Check and Build for Saleor Storefront
#   - name: 'gcr.io/cloud-builders/git'
#     id: 'Check Saleor Storefront'
#     entrypoint: 'bash'
#     args:
#     - '-c'
#     - |
#       if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'saleor-storefront/'; then
#         echo "Changes detected in Storefront, proceeding with build."
#         gcloud builds submit --config=saleor-storefront/cloudbuild.yaml --substitutions=_SERVICE_NAME="saleor-storefront",_DOCKERFILE_PATH="saleor-storefront/Dockerfile",_BUILD_CONTEXT="saleor-storefront"
#       else
#         echo "No changes in Storefront, skipping build."
#       fi
#     dir: 'saleor-storefront/'

# timeout: '1200s'
