steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Fetch more history to ensure we can access $COMMIT_SHA^
        git fetch --depth=500

        # Check if the previous commit exists
        if git rev-parse $COMMIT_SHA^ >/dev/null 2>&1; then
          echo "Parent commit exists, proceeding with build steps."
        else
          echo "Parent commit does not exist, fetching more history."
          git fetch --unshallow
        fi

        # Now perform the intended Git operations
        if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'saleor-core/'; then
          echo "Changes detected in saleor-core, proceeding with build."
          gcloud builds submit --config saleor-core/cloudbuild.yaml .
        else
          echo "No changes in saleor-core, skipping build."
        fi
  # Step for Saleor Core
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'saleor-core/cloudbuild-saleor-core.yaml', '${_GCS_SOURCE_STAGING_DIR}']
    dir: 'saleor-core/'
    id: 'Build Saleor Core'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'saleor-core/'; then
        gcloud builds submit --config saleor-core/cloudbuild.yaml .
      else
        echo "Skipping Saleor Core build, no changes detected."
      fi

  # Step for Saleor Dashboard
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'saleor-dashboard/cloudbuild-saleor-dashboard.yaml', '${_GCS_SOURCE_STAGING_DIR}']
    dir: 'dashboard/'
    id: 'Build Saleor Dashboard'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'dashboard/'; then
        gcloud builds submit --config saleor-dashboard/cloudbuild.yaml .
      else
        echo "Skipping Dashboard build, no changes detected."
      fi

  # Step for Saleor Storefront
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'saleor-storefront/cloudbuild-saleor-storefront.yaml', '${_GCS_SOURCE_STAGING_DIR}']
    dir: 'saleor-storefront/'
    id: 'Build Saleor Storefront'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'saleor-storefront/'; then
        gcloud builds submit --config saleor-storefront/cloudbuild.yaml .
      else
        echo "Skipping Storefront build, no changes detected."
      fi
