steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Current commit: $COMMIT_SHA" &&
        git fetch --depth=2 && 
        if [ "$(git rev-list --count HEAD)" -eq "1" ]; then
          echo "This is the first commit, running all builds." &&
          gcloud builds submit --config saleor-core/saleorcore-build.yaml &&
          gcloud builds submit --config saleor-dashboard/dashboard-build.yaml &&
          gcloud builds submit --config saleor-storefront/storefront-build.yaml
        else
          CHANGED_FILES="$(git diff --name-only $COMMIT_SHA^ $COMMIT_SHA)" &&
          echo "Changed files: $CHANGED_FILES" &&
          echo "$CHANGED_FILES" | grep -E '^saleor-core/' &&
          if [ $? -eq 0 ]; then
            echo "Changes detected in saleor-core" &&
            gcloud builds submit --config saleor-core/saleorcore-build.yaml
          fi &&
          echo "$CHANGED_FILES" | grep -E '^saleor-dashboard/' &&
          if [ $? -eq 0 ]; then
            echo "Changes detected in saleor-dashboard" &&
            gcloud builds submit --config saleor-dashboard/dashboard-build.yaml
          fi &&
          echo "$CHANGED_FILES" | grep -E '^saleor-storefront/' &&
          if [ $? -eq 0 ]; then
            echo "Changes detected in saleor-storefront" &&
            gcloud builds submit --config saleor-storefront/storefront-build.yaml
          fi
        fi
