steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'saleor-cluster'
      - '--region'
      - 'europe-west1'
      - '--project'
      - 'saleor-lab-oyqg'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=europe-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=saleor-cluster'
      - 'KUBECTL_VERSION=1.27'

  # Apply all Kubernetes configurations from the deployment directory and its subdirectories
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'find deployment/ -type f -name "*.yaml" -or -name "*.yml" | xargs kubectl apply -f'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=europe-west1'  
      - 'CLOUDSDK_CONTAINER_CLUSTER=saleor-cluster'


#   # Update image for saleor-core
#   - name: 'gcr.io/cloud-builders/kubectl'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         if kubectl get deployment saleor-core --namespace=default; then
#           kubectl set image deployment/saleor-core saleor-dashboard=europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-dashboard:$COMMIT_SHA --namespace=default
#         fi
#     dir: 'deployment'
#     env:
#       - 'CLOUDSDK_COMPUTE_REGION=europe-west1'  
#       - 'CLOUDSDK_CONTAINER_CLUSTER=saleor-cluster'

#   # Update image for API deployment
#   - name: 'gcr.io/cloud-builders/kubectl'
#     args:
#       - 'set'
#       - 'image'
#       - 'deployment/api'
#       - 'api=europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-core:$COMMIT_SHA'
#       - '--namespace=default'
#     env:
#       - 'CLOUDSDK_COMPUTE_REGION=europe-west1'  
#       - 'CLOUDSDK_CONTAINER_CLUSTER=saleor-cluster'

#   # Update the image for the Worker deployment
#   - name: 'gcr.io/cloud-builders/kubectl'
#     args:
#       - 'set'
#       - 'image'
#       - 'deployment/worker'
#       - 'worker=europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-core:$COMMIT_SHA'
#       - '--namespace=default'
#     env:
#       - 'CLOUDSDK_COMPUTE_REGION=europe-west1'  
#       - 'CLOUDSDK_CONTAINER_CLUSTER=saleor-cluster'

#   # Update the image for saleor-frontend if deployment exists
#   - name: 'gcr.io/cloud-builders/kubectl'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         if kubectl get deployment saleor-frontend --namespace=default; then
#           kubectl set image deployment/saleor-frontend saleor-frontend=europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-storefront:$COMMIT_SHA --namespace=default
#         fi
#     dir: 'deployment'
#     env:
#       - 'CLOUDSDK_COMPUTE_REGION=europe-west1'  
#       - 'CLOUDSDK_CONTAINER_CLUSTER=saleor-cluster'

# images:
#   - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-core:$COMMIT_SHA'
#   - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-dashboard:$COMMIT_SHA'
#   - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-storefront:$COMMIT_SHA'

# timeout: '1200s'
