steps:

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Check Saleor Core'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
       
            gcloud builds submit --config ./saleor-core/saleorcore-build.yaml --substitutions=COMMIT_SHA=$COMMIT_SHA .
      
    
  # Check changes in the saleor-dashboard directory
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          gcloud builds submit --config saleor-dashboard/dashboard-build.yaml --substitutions=COMMIT_SHA=$COMMIT_SHA .
        

  # Check changes in the saleor-storefront directory
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          gcloud builds submit --config saleor-storefront/storefront-build.yaml --substitutions=COMMIT_SHA=$COMMIT_SHA .
substitutions:
  _SHORT_SHA: '${SHORT_SHA}'