steps:
  - name: 'gcr.io/cloud-builders/git'
    id: 'Check Saleor Core'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      # Determine the number of commits
      COMMIT_COUNT=$(git rev-list --count HEAD)
      
      # Check if there are more than one commit to safely use git diff with COMMIT_SHA^
      if [ "$COMMIT_COUNT" -gt 1 ]; then
        # If there are changes in the saleor-core directory between the last and current commit
        if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'saleor-core/'; then
          echo "Changes detected in Saleor Core, proceeding with build."
          # Submit a Cloud Build using the configuration file for saleor-core
          gcloud builds submit --config=saleor-core/saleorcore-build.yaml --substitutions=_SERVICE_NAME="saleor-core",_DOCKERFILE_PATH="Dockerfile",_BUILD_CONTEXT="."
        else
          echo "No changes in Saleor Core, skipping build."
        fi
      else
        # Handle the first commit differently by building all services
        echo "First commit detected. Proceeding with build of Saleor Core as no historical diff is available."
        gcloud builds submit --config=saleor-core/saleorcore-build.yaml --substitutions=_SERVICE_NAME="saleor-core",_DOCKERFILE_PATH="Dockerfile",_BUILD_CONTEXT="."
      fi
    dir: 'saleor-core/'


  # # Check changes in the saleor-dashboard directory
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'saleor-dashboard/'; then
  #         gcloud builds submit --config saleor-dashboard/cloudbuild.yaml --substitutions=COMMIT_SHA=$COMMIT_SHA .
  #       fi

  # # Check changes in the saleor-storefront directory
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'saleor-storefront/'; then
  #         gcloud builds submit --config saleor-storefront/cloudbuild.yaml --substitutions=COMMIT_SHA=$COMMIT_SHA .
  #       fi
