steps:
   # Setup git credentials using the secret directly
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Fetch the token from Secret Manager and write it to a git credentials file
        echo "https://${SECRET_GITHUB_TOKEN}:x-oauth-basic@github.com" > /root/.git-credentials
        git config --global credential.helper 'store --file=/root/.git-credentials'
        
        # Fetch the repository with deeper history if needed
        git fetch --unshallow || git fetch --depth=500

  # Build the Docker image from the 'saleor-core/' directory
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-core:${SHORT_SHA}'
      - '.'
    dir: 'saleor-core/'

  # Push the built image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-core:${SHORT_SHA}'


# Specify which images to store in Container Registry
images:
  - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-core:${SHORT_SHA}'



# Specify the secrets required for this build
availableSecrets:
  secretManager:
    - versionName: projects/saleor-lab-oyqg/secrets/github-token/versions/latest
      


  # # Step 1: Build the Docker image
  # - name: 'gcr.io/cloud-builders/docker'
  #   dir: 'saleor-core'  
  #   args:
  #     - 'build'
  #     - '-t'
  #     - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-core:$COMMIT_SHA'
  #     - '.' 
  # # Step 2: Push the image to Google Artifact Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'push'
  #     - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-core:$COMMIT_SHA'

# images:
#   - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-core:$COMMIT_SHA'



# steps:
  # # Check and Build for Saleor Core
  # - name: 'gcr.io/cloud-builders/git'
  #   id: 'Check Saleor Core'
  #   entrypoint: 'bash'
  #   args:
  #   - '-c'
  #   dir: 'saleor-core/'

#   # Check and Build for Saleor Dashboard
#   - name: 'gcr.io/cloud-builders/git'
#     id: 'Check Saleor Dashboard'
#     entrypoint: 'bash'
#     args:
#     - '-c'
#     - |
#       if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'dashboard/'; then
#         echo "Changes detected in Dashboard, proceeding with build."
#         gcloud builds submit --config=dashboard/cloudbuild.yaml --substitutions=_SERVICE_NAME="saleor-dashboard",_DOCKERFILE_PATH="dashboard/Dockerfile",_BUILD_CONTEXT="dashboard"
#       else
#         echo "No changes in Dashboard, skipping build."
#       fi
#     dir: 'dashboard/'

#   # Check and Build for Saleor Storefront
#   - name: 'gcr.io/cloud-builders/git'
#     id: 'Check Saleor Storefront'
#     entrypoint: 'bash'
#     args:
#     - '-c'
#     - |
#       if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'saleor-storefront/'; then
#         echo "Changes detected in Storefront, proceeding with build."
#         gcloud builds submit --config=saleor-storefront/cloudbuild.yaml --substitutions=_SERVICE_NAME="saleor-storefront",_DOCKERFILE_PATH="saleor-storefront/Dockerfile",_BUILD_CONTEXT="saleor-storefront"
#       else
#         echo "No changes in Storefront, skipping build."
#       fi
#     dir: 'saleor-storefront/'

# timeout: '1200s'
