steps:
  # Set the new image for the Kubernetes Deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deploy/saleor-core', 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-core:$COMMIT_SHA']
    dir: 'deployment'
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'saleor-core/'
    args: 
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-core:${SHORT_SHA}'
      - '.'

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-core:${SHORT_SHA}'

# Specify images to be stored in the Container Registry
images:
  - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-core:${SHORT_SHA}'

# Set a timeout for the build
timeout: '1200s'


  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deploy/saleor-dashboard', 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-dashboard:$COMMIT_SHA', '--namespace=saleor']
    dir: 'deployment'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deploy/saleor-frontend', 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-storefront:$COMMIT_SHA', '--namespace=saleor']
    dir: 'deployment'

  # Apply all other Kubernetes configuration files (e.g., services, configmaps)
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', '.']
    dir: 'deployment'

images:
  - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor:$COMMIT_SHA'
  - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-dashboard:$COMMIT_SHA'
  - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-storefront:$COMMIT_SHA'

timeout: '1200s'  
