steps:
   # Step to fetch more history for proper diff (if required)
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      if git rev-parse $COMMIT_SHA^ >/dev/null 2>&1; then
        echo "Parent commit exists, proceeding with build checks."
      else
        echo "Fetching more history for diff checks..."
        git fetch --deepen=50
        if git rev-parse $COMMIT_SHA^ >/dev/null 2>&1; then
          echo "History is now sufficient for diff."
        else
          echo "Still unable to find parent commit, skipping specific build steps based on paths."
          exit 0
        fi
      fi
  # Step for Saleor Core
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'saleor-core/cloudbuild-saleor-core.yaml', '${_GCS_SOURCE_STAGING_DIR}']
    dir: 'saleor-core/'
    id: 'Build Saleor Core'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'saleor-core/'; then
        gcloud builds submit --config saleor-core/cloudbuild.yaml .
      else
        echo "Skipping Saleor Core build, no changes detected."
      fi

  # Step for Saleor Dashboard
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'saleor-dashboard/cloudbuild-saleor-dashboard.yaml', '${_GCS_SOURCE_STAGING_DIR}']
    dir: 'dashboard/'
    id: 'Build Saleor Dashboard'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'dashboard/'; then
        gcloud builds submit --config saleor-dashboard/cloudbuild.yaml .
      else
        echo "Skipping Dashboard build, no changes detected."
      fi

  # Step for Saleor Storefront
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'saleor-storefront/cloudbuild-saleor-storefront.yaml', '${_GCS_SOURCE_STAGING_DIR}']
    dir: 'saleor-storefront/'
    id: 'Build Saleor Storefront'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'saleor-storefront/'; then
        gcloud builds submit --config saleor-storefront/cloudbuild.yaml .
      else
        echo "Skipping Storefront build, no changes detected."
      fi
