steps:
  - name: 'gcr.io/cloud-builders/git'
    id: 'Check Saleor Core'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      cd saleor/core
      git fetch --depth=2
      git log
      # Determine if there are more than one commit to enable using git diff
      if [ $(git rev-list --count HEAD) -gt 1 ]; then
        # Check for changes in the saleor-core directory
        if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'saleor-core/'; then
          echo "Changes detected in Saleor Core, proceeding with build."
          gcloud builds submit --config saleorcore-build.yaml
        else
          echo "No changes in Saleor Core, skipping build."
        fi
      else
        # If it's the first commit, just build everything
        echo "First commit detected, building all components."
        gcloud builds submit --config saleorcore-build.yaml
      fi

  # # Check changes in the saleor-dashboard directory
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'saleor-dashboard/'; then
  #         gcloud builds submit --config saleor-dashboard/cloudbuild.yaml --substitutions=COMMIT_SHA=$COMMIT_SHA .
  #       fi

  # # Check changes in the saleor-storefront directory
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -q 'saleor-storefront/'; then
  #         gcloud builds submit --config saleor-storefront/cloudbuild.yaml --substitutions=COMMIT_SHA=$COMMIT_SHA .
  #       fi
