apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: allistore-worker
  name: allistore-worker
  namespace: default
spec:
  selector:
    matchLabels:
      app: allistore-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: allistore-worker
    spec:
      containers:
      - args:
        - celery
        - -A
        - saleor
        - --app=saleor.celeryconf:app
        - worker
        - --loglevel=info
        - -B
        envFrom:
        - configMapRef:
            name: allistore-common
        - configMapRef:
            name: allistore-backend
        image: ghcr.io/saleor/saleor:3.15.6
        imagePullPolicy: IfNotPresent
        name: allistore-worker
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
