apiVersion: v1
kind: Service
metadata:
  name: allistore-db
  namespace: default
spec:
  ports:
  - name: allistore-db
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: allistore-db
