apiVersion: v1
kind: Service
metadata:
  name: allistore-api
  namespace: default
spec:
  ports:
  - name: allistore-api
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: allistore-api
  type: LoadBalancer
