
apiVersion: v1
kind: Service
metadata:
  name: allistore-redis
  namespace: default
spec:
  ports:
  - name: allistore-redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: allistore-redis
