steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'us-central1-docker.pkg.dev/my-gcloud-project/my-artifacts/${_SERVICE_NAME}:${SHORT_SHA}', 
      '-f', 
      '${_DOCKERFILE_PATH}', 
      '.'
    ]
    dir: '${_BUILD_CONTEXT}'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/${_SERVICE_NAME}:${SHORT_SHA}'
    ]

substitutions:
  _SERVICE_NAME: 'saleor-worker'
  _DOCKERFILE_PATH: 'Dockerfile' 
  _BUILD_CONTEXT: '.' 

images:
  - 'europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/${_SERVICE_NAME}:${SHORT_SHA}'


tags:
  - 'artifact-registry-push'
