steps:


- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - 'saleor-cluster'
    - '--region'
    - 'europe-west1'
    - '--project'
    - 'saleor-lab-oyqg'


# Build and push the backend Docker image if the backend has changed
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-api'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      
        DOCKER_BUILDKIT=1 docker build -t europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor:${SHORT_SHA} 
        docker push europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor:${SHORT_SHA}
    
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'deploy-api'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
     
        kubectl set image deployment/allistore-api allistore-api=europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor:${SHORT_SHA}
  
      
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'deploy-worker'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
     
        kubectl set image deployment/allistore-worker allistore-worker=europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor:${SHORT_SHA}



substitutions:
  _SHORT_SHA: '${SHORT_SHA}'