apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: allistore-storefront
  name: allistore-storefront
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allistore-storefront
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: allistore-storefront
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: allistore-common
        image: ghcr.io/reinventex/allistore-storefront:v1.0
        imagePullPolicy: IfNotPresent
        name: allistore-storefront
        ports:
        - containerPort: 3000
          name: shiva-store
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 250Mi
