apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: allistore-worker
  name: allistore-worker
  namespace: default
spec:
  selector:
    matchLabels:
      app: allistore-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: allistore-worker
    spec:
      containers:
      - args:
        - celery
        - -A
        - saleor
        - --app=saleor.celeryconf:app
        - worker
        - --loglevel=info
        - -B
        envFrom:
        - configMapRef:
            name: allistore-common
        - configMapRef:
            name: allistore-backend

        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 300m
            memory: 300Mi   
        image: europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor:latest
        imagePullPolicy: IfNotPresent
        name: allistore-worker
      dnsPolicy: ClusterFirst
      restartPolicy: Always
