name: Build and Push Saleor Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'saleor-core/**'
      - 'saleor-storefront/**'
      - 'saleor-dashboard/**'

jobs:
  build-core:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Google Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: europe-west1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}
    - name: Build and push Docker image for Saleor Core
      uses: docker/build-push-action@v2
      with:
        context: ./saleor-core
        file: ./saleor-core/Dockerfile
        push: true
        tags: europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor:latest

  # Repeat similar steps for storefront and dashboard without 'if' conditions


# name: Build and Push Saleor Docker Images

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'saleor-core/**'
#       - 'saleor-storefront/**'
#       - 'saleor-dashboard/**'

# jobs:
#   build-core:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1
#     - name: Log in to Google Artifact Registry
#       uses: docker/login-action@v1
#       with:
#         registry: europe-west1-docker.pkg.dev
#         username: _json_key
#         password: ${{ secrets.GCP_SA_KEY }}
#     - name: Build and push Docker image for Saleor Core
#       uses: docker/build-push-action@v2
#       with:
#         context: ./saleor-core
#         file: ./saleor-core/Dockerfile
#         push: true
#         tags: europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor:latest

#   # Repeat similar steps for storefront and dashboard without 'if' conditions
