
name: Build and Push Saleor Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'saleor-core/**'
      - 'saleor-storefront/**'
      - 'saleor-dashboard/**'

jobs:
  build-core:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'saleor-core/') }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  
      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v2  
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
      - name: Build and push Docker image for Saleor Core
        uses: docker/build-push-action@v3 
        with:
          context: ./saleor-core
          file: ./saleor-core/Dockerfile
          push: true
          tags: europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor:latest

  build-storefront:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'saleor-storefront/') }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
      - name: Build and push Docker image for Custom Storefront
        uses: docker/build-push-action@v3
        with:
          context: ./saleor-storefront
          file: ./saleor-storefront/Dockerfile
          push: true
          tags: europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-storefront:latest

  build-dashboard:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'saleor-dashboard/') }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
      - name: Build and push Docker image for Saleor Dashboard
        uses: docker/build-push-action@v3
        with:
          context: ./saleor-dashboard
          file: ./saleor-dashboard/Dockerfile
          push: true
          tags: europe-west1-docker.pkg.dev/saleor-lab-oyqg/images/saleor-dashboard:latest
          build-args: |
            API_URI=https://api.allistore.uk/graphql/
            APP_MOUNT_URI=/
            STATIC_URL=/
            MARKETPLACE_URL=https://apps.saleor.io/
            SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps
            IS_CLOUD_INSTANCE=false