name: Deploy GCP Infra Changes

on:
  push:
    branches:
      - "f/terraform"  
    paths:
      - 'terraform/**'  

jobs:
  terraform-validator:
    runs-on: ubuntu-latest
    env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
        PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}
        GITHUB_PAT: ${{ secrets.MYGITHUB_PAT }}
        APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
        REGION: ${{ secrets.REGION }}
        REPO_NAME: ${{ secrets.REPO_NAME }}
        NETWORK_NAME: ${{ secrets.NETWORK_NAME }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  

      - name: 'Setup Google Cloud Credentials'
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_ACTION }}
          export_default_credentials: true

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7  

      - name: "Terraform format"
        run: |
          cd terraform/lab  
          terraform fmt  
      - name: "Terraform init"
        run: |
          cd terraform/lab
          terraform init -input=false  

      - name: "Terraform plan"
        if: ${{ github.event_name == 'push' }}
        run: |
          cd terraform/lab
          terraform plan -input=false -no-color  

      - name: "Terraform apply"
        if: ${{ github.ref == 'refs/heads/f/terraform' && github.event_name == 'push' }}
        run: |
          cd terraform/lab
          terraform apply -input=false -auto-approve 
