name: Deploy GCP Infra Changes

on:
  push:
    branches:
      - "f/terraform"  
    paths:
      - 'terraform/**'  

jobs:
  terraform-validator:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  

      - name: 'Setup Google Cloud Credentials'
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7  

      - name: "Terraform format"
        run: |
          cd terraform/lab  
          terraform fmt  

      - name: "Terraform init"
        run: |
          cd terraform/lab
          terraform init -input=false  

      - name: "Terraform plan"
        run: |
          cd terraform/lab
          terraform plan -var="mygithub_token=${{ secrets.MYGITHUB_TOKEN }}" \
                          -var="project_id=${{ secrets.PROJECT_ID }}" \
                          -var="project_number=${{ secrets.PROJECT_NUMBER }}" \
                          -var="mygithub_pat=${{ secrets.MYGITHUB_PAT }}" \
                          -var="app_installation_id=${{ secrets.APP_INSTALLATION_ID }}" \
                          -var="region=${{ secrets.REGION }}" \
                          -var="repo_name=${{ secrets.REPO_NAME }}" \
                          -var="network_name=${{ secrets.NETWORK_NAME }}"

      - name: "Terraform apply"
        if: ${{ github.ref == 'refs/heads/f/terraform' && github.event_name == 'push' }}
        run: |
          cd terraform/lab
          terraform apply -auto-approve -var="mygithub_token=${{ secrets.MYGITHUB_TOKEN }}" \
                                                      -var="project_id=${{ secrets.PROJECT_ID }}" \
                                                      -var="project_number=${{ secrets.PROJECT_NUMBER }}" \
                                                      -var="mygithub_pat=${{ secrets.MYGITHUB_PAT }}" \
                                                      -var="app_installation_id=${{ secrets.APP_INSTALLATION_ID }}" \
                                                      -var="region=${{ secrets.REGION }}" \
                                                      -var="repo_name=${{ secrets.REPO_NAME }}" \
                                                      -var="network_name=${{ secrets.NETWORK_NAME }}"
