name: Terraform Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**' 
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.0' 

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/lab
    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: terraform plan
      working-directory: ./terraform/lab 
    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve
      working-directory: ./terraform/lab